### ISSUE TITLE
Проект всё?

### ISSUE THREAD

**Issue by dmitrydvm** [Supreme85/VIQAUITestingTool#2]
Здравствуйте.
Ищу Фреймворк для автоматизации ui на дотнете.
Проект еще жив?

**Comment by RomanIovlev** [comment]
Привет,

Жив, но давно не поддерживался )
Проект сейчас переживает новую инкарнацию именуемую JDI, но есть только
Java версия, .Net в процессе,
Но в принципе можно пользоваться и VIQA, она вполне в работоспособном
состоянии

Роман

2 марта 2016 г., 17:09 пользователь Dmitry notifications@github.com
написал:

**Comment by dmitrydvm** [comment]
Если есть возможность, добавьте, пожалуйста, поддержку Nunit 3.

**Comment by RomanIovlev** [comment]
Мы сейчас переписывем проект в его новой инкарнации JDI. VIQA больше
поддерживаться не будет.
Первая верссия новой инкарнации будет готова к концу марта
Теперь это не только моя разработка, но и комании Epam (у нас целая
команда). Уже есть гораздо более функциональная версия чем VIQA на Java
(есть документация и всякие примеры исползования, будет также сайт). Сейчас
портируем ее на C#.
Java версия пока лежит тут
https://github.com/ggasoftware/gga-selenium-framework скорее всего C#
положим рядом, в любом случае ссылки на сайт и C# версию будут тут.
Также если интересно вот презентации возможностей нового Фреймворка.
https://drive.google.com/file/d/0B958oJxLdPHgWmhidno3UkxzQUU/view4
https://drive.google.com/file/d/0B958oJxLdPHgWmhidno3UkxzQUU/view -
последняя внутренняя презентация для Инженеров (Январь 2016)
https://drive.google.com/file/d/0B958oJxLdPHgaU40UWJlNjNqSms/view1
https://drive.google.com/file/d/0B958oJxLdPHgaU40UWJlNjNqSms/view -
старая внутренняя презентация для Инженеров (Сентябрь 2015)
https://drive.google.com/file/d/0B958oJxLdPHgVkM2Q3IxRDg5Ync/view3
https://drive.google.com/file/d/0B958oJxLdPHgVkM2Q3IxRDg5Ync/view -
(бизнес презентация) новая презентация для Менеджеров/Клиента (Февраль 2016)

P.S. ваше пожелание на счет NUnit 3 учтем ) Спасибо

2016-03-09 12:15 GMT+03:00 Dmitry notifications@github.com:

**Comment by dmitrydvm** [comment]
Я всё-таки использую VIQA. Подскажите, пожалуйста, как вынести урл сайта в App.config. Точнее как сделать так, чтобы указывать урл не в атрибуте класса сайта? Или как передать его в атрибут?
